apiVersion: v1
kind: Service
metadata:
  name: mcp-server-seuk-svc
  namespace: agenticai-demo
  labels:
    app.kubernetes.io/name: mcp-server-seuk
    app.kubernetes.io/part-of: agenticai-demo
    app.kubernetes.io/component: mcp-server-seuk
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mcp-server-seuk
  ports:
    - name: http
      port: 3001
      targetPort: 3001
      protocol: TCP
