apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  instances: 1
  db:
    vendor: postgres
    host: postgres-db
    port: 5432
    database: keycloak
    usernameSecret:
      name: keycloak-db-secret
      key: username
    passwordSecret:
      name: keycloak-db-secret
      key: password
  http:
    httpEnabled: true
    httpPort: 8080
    httpsPort: 8443
  hostname:
    hostname: keycloak-keycloak.apps.demo-0847.miscplatform.io
    strict: false
    strictBackchannel: false
  startOptimized: false
  proxy:
    headers: xforwarded
  additionalOptions:
    - name: log-level
      value: INFO
